version: "3.8"

services:

  localstack:
    container_name: localstack
    image: localstack/localstack:1.0.3 # NOTE: I've tried version above this one, but it didn't work.
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - LOCALSTACK_HOSTNAME=localhost.localstack.cloud  # set this env var to expose localstack to other containers
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_DEFAULT_REGION=eu-west-1
      - SERVICES=sns,sqs,dynamodb,lambda
      - LAMBDA_DOCKER_NETWORK=springboot-aws-localstack-dynamodb-lambda-sns-sqs_default
      # ---
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker-reuse} # important config so that lambda works
      - LAMBDA_REMOTE_DOCKER=false                      # important config so that lambda works
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}       # only required for Pro
      - HOST_TMP_FOLDER=$PWD/tmp/folder
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "$PWD/tmp/localstack:/var/lib/localstack"
      - "$PWD/dynamodb-lambda-function/shared:/dynamodb-lambda-function/shared"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      default:
        aliases:
          - localhost.localstack.cloud   # set this network aliases to expose localstack to other containers
